# Stage 1: Building the application
FROM node AS builder
WORKDIR /app
COPY . .

RUN npm ci
RUN npm run build

# Stage 2: Run the application
FROM node
WORKDIR /app

# Copy the build from the previous stage
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/public ./public
COPY --from=builder /app/package*.json ./

# Expose the port the app runs on
EXPOSE 3000

# Define the command to run your app
CMD ["npm", "start"]
