import type { Metadata } from "next";
import "./globals.css";

import { Web3Modal } from "@/context/Web3Modal";

export const metadata: Metadata = {
  title: "DEEP YOUR DRINK",
  description: "Generated by alcohol and kebab",
  viewport:
    "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0",
};

import "./globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Web3Modal>{children}</Web3Modal>
      </body>
    </html>
  );
}
